In [4]:
import numpy as np
np.__version__

'1.18.1'

In [7]:
L = list(range(10))
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
[str(c) for c in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
np.zeros(10,dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((3,5),1.77)

array([[1.77, 1.77, 1.77, 1.77, 1.77],
       [1.77, 1.77, 1.77, 1.77, 1.77],
       [1.77, 1.77, 1.77, 1.77, 1.77]])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [17]:
np.random.normal(0,1,(3,3))

array([[-0.00136448,  0.02376282, -0.94606339],
       [-1.28853131,  0.43039948,  0.32486044],
       [-0.84163548, -0.41703888, -0.74302619]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.seed(0)

In [26]:
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

print(x1)

print(x2)

print(x3)

print('x1 ndim:',x1.ndim)
print('x2 ndim:',x2.ndim)
print('x3 ndim:',x3.ndim)

[8 5 4 7 4 1]
[[3 3 9 2]
 [5 2 3 5]
 [7 2 7 1]]
[[[6 5 0 0 3]
  [1 9 9 6 6]
  [7 8 8 7 0]
  [8 6 8 9 8]]

 [[3 6 1 7 4]
  [9 2 0 8 2]
  [7 8 4 4 1]
  [7 6 9 4 1]]

 [[5 9 7 1 3]
  [5 7 3 6 6]
  [7 9 1 9 6]
  [0 3 8 4 1]]]
x1 ndim: 1
x2 ndim: 2
x3 ndim: 3


In [27]:
x1 = np.array([4,3,5,6,8,9])
x1

array([4, 3, 5, 6, 8, 9])

In [28]:
x1[0]

4

In [29]:
x1[4]

8

In [30]:
x1[-1]

9

In [31]:
x1[-2]

8

In [36]:
x2=np.array([[3,7,5,5],
          [0,1,5,9],
          [3,0,5,0]])

In [37]:
x2[2,3]

0

In [38]:
x2[2,-1]

0

In [40]:
x2[0,0] = 12
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

In [41]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[0:5]

array([0, 1, 2, 3, 4])

In [44]:
x[4:]

array([4, 5, 6, 7, 8, 9])

In [45]:
x[4:7]

array([4, 5, 6])

In [46]:
x[ : :2]

array([0, 2, 4, 6, 8])

In [48]:
x[1: :2]

array([1, 3, 5, 7, 9])

In [49]:
x[ : :-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [50]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = [21,22,21]

np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 22, 21])

In [53]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [56]:
x =np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
np.vstack([x,grid])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [57]:
z =np.array([[9],[9]])
np.hstack([grid,z])

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

In [58]:
x =np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])